### ISSUE TITLE
turbovnc server crashing on ARM based chroot

### ISSUE THREAD

**Issue by Cpmos** [TurboVNC/turbovnc#151]
turbovnc server runs fine for minutes/ sometimes hours and sometimes even for days and then crashes. there are no issues to be found in the log files. When doing nothing no crashes occur.  It usually happens when a window is being closed on the Xsession, sometimes the crash occurs at random however. Tried different VNC clients, effect remains. Crashes get worse when browser window is open or when music is playing. Other Xvnc based vnc servers do not show this behaviour. In very rare cases the server hangs completely not responding to normal terminate signals.

These turbovnc sessions are running on a ubuntu 18.04 chroot on ARM64. Somewhat of a unique setting I am aware.

First bug report on your code. Please instruct me on which logs, info, debug data you need to at least get a hint of whats going on. Very happy to comply.

**Comment by dcommander** [comment]
Pass `-DCMAKE_BUILD_TYPE=RelWithDebInfo` to `cmake` when configuring the build, then rebuild the server.  That will cause debugging symbols to be included in the Xvnc executable, which will allow a stack trace to be obtained whenever the crash occurs.  If the crash is readily reproducible, then simply attach GDB to the Xvnc process prior to the crash, then use the `where` command in GDB to obtain a stack trace, once the crash occurs.  If the crash is unpredictable, then run `ulimit -c 10000000` prior to starting the server, which will cause Xvnc to dump a core file when it crashes.  Then you can execute `gdb {path_to_Xvnc} {path_to_core_file}` and then use the `where` command in GDB to obtain a stack trace.

There is only a limited amount I can do to debug a crash without being able to reproduce it, but please send me:
* The aforementioned stack trace from Xvnc, when it crashes
* The TurboVNC session log (__~/.vnc/{hostname}:{display_number}.log__ on the server)
* The arguments you passed to the __vncserver__ script when starting the server, if any

**Comment by Cpmos** [comment]
Building latest libjpeg-turbo and master. Will thoroughly test and report the results.

**Comment by dcommander** [comment]
OK, cool.  Make sure you pull the commits I just pushed a few minutes ago, as they may affect this issue.

**Comment by Cpmos** [comment]
still crashing. Will rebuild with debug symbols and get a stack trace. Have some clear routes to reproduce the bug in a fairly easy way. Will report after building and testing.

**Comment by dcommander** [comment]
No problem.  I'm trying to fix as many bugs as possible prior to the 2.2.1 release later this month, so I welcome any bug reports.

**Comment by dcommander** [comment]
I can't imagine how it could be.  To the best of my understanding, ulimit only affects the behavior after the crash occurs, not before.  Are you sure that's the only thing that changed?

**Comment by dcommander** [comment]
The reason I ask is that, sometimes, building with debug symbols *can* eliminate a crash.

**Comment by Cpmos** [comment]
now that you mentioned it. I had another xserver running on the same machine that I killed before starting the debugging build. Maybe the second instance of Xvnc is interfering. This is a strange machine after all. Will test some more.

**Comment by dcommander** [comment]
What I'm saying is that, if you noticed the crash only with Release builds and not ever with RelWithDebInfo builds, it could be that the presence of the debugging symbols is preventing the crash.  I have seen that before.

**Comment by dcommander** [comment]
Also, be aware that I have been fixing some valgrind warnings in the master branch, so if you've been pulling from master while diagnosing this bug, you may have pulled a commit that accidentally fixed the crash.

**Comment by Cpmos** [comment]
finally crashed it. cannot locate the core file you mentioned however. will upload logs etc soon.

**Comment by Cpmos** [comment]
[localhost:1.log](https://github.com/TurboVNC/turbovnc/files/2659994/localhost.1.log)
the log of the crash this time showing a signal 6. But sometimes its a signal 11.

Started it like this: ./vncserver :1 -geometry 1920x1080 -localhost -depth 24 -dpi 144 -deferupdate 0 -alrsamp gray -nointerframe -nomt -alrqual 100

tried with and without -nomt and -alrqual. These commands are all an attempt to speed up the screen refresh times since this is a local vnc session.

Found a *.pid file of 6 bytes I bet thats not a good core dump.

**Comment by Cpmos** [comment]
Ok. Finally managed to even get the debug build crashing. Resizing alot of windows etc. does the trick. Now after hours of trying googling and figuring I have indication that the lack of a core file after crash has to do with the chroot not handling this very well. So no core file after crash... I tried attaching the running Xvnc process into gdb but then the process stops. When using the continue command other annoying stuff happens. Any ideas how to get a good bug trace?

**Comment by dcommander** [comment]
If it's possible to run valgrind in the chroot environment, I would try that next.  It may make the crash impossible, due to changing the timing, but it will also print stack traces any time it encounters a problem that could lead to a crash.  What you seem to be encountering is a double free, which is a more serious issue than the issues I just fixed in master.  If you have Clang available in the chroot environment, then you might also want to try building TurboVNC with ASan (https://clang.llvm.org/docs/AddressSanitizer.html).  That is less disruptive than valgrind, so it might allow the crash to occur, and it will print information about where in the code it occurs.

**Comment by dcommander** [comment]
Also, I tried the command-line options you specified, just as a sanity check, but I was unable to reproduce any errors with valgrind.  Note also:
* `-alrsamp` and `-alrqual` have no effect unless `-alr` is also specified.
* You should never pass a display number to `vncserver`, since `vncserver` allocates one automatically.
* `-depth 24` is the default in TurboVNC and need not be specified.
* `-deferupdate 0` will basically disable any coalescing of X11 updates into RFB framebuffer updates, which is a very bad idea in a production environment.  Also, if you were doing that in an attempt to make the server crash, you may have made the crash less likely.

**Comment by dcommander** [comment]
Also, in order to use valgrind, you will need to invoke it directly on the Xvnc process.  I generally do that by modifying the vncserver script as such:

```
@@ -465,7 +465,7 @@
 
 # Now start the TurboVNC X server
 
-$cmd = $exedir."Xvnc :$displayNumber";
+$cmd = "valgrind ".$exedir."Xvnc :$displayNumber";
 $cmd .= " -dpi $dpi" if ($dpi);
 $cmd .= " -desktop " . &quotedString($desktopName);
 $cmd .= " -httpd $vncClasses" if ($enableHTTP && $vncClasses);
```

If you don't do that, then valgrind will monitor the Perl process, not the Xvnc process.

**Comment by Cpmos** [comment]
valgrind works however the adaption to the perl script doesn' t. Tried running the binary directly through valgrind, it runs but crashes as it normally would when running it directly. The script says it started the xserver on screen :x but no Xvnc ever got started.

What detail am I missing here?

**Comment by dcommander** [comment]
Impossible for me to say.  I can't read your mind and thus have no idea what you mean by "the adaption of the perl script doesn't [work]."  How specifically is it failing?  Post the console output, please, as well as a more thorough description.

**Comment by Cpmos** [comment]
Ok I think valgrind does actually start. This is the process spawned after running the server.
14816 pts/2    00:00:03 memcheck-arm64-

$ ./vncserver -localhost

Desktop 'TurboVNC: localhost:1 (android)' started on display localhost:1

Starting applications specified in /home/android/.vnc/xstartup.turbovnc
Log file is /home/android/.vnc/localhost:1.log

Everything is up and running. However only a black screen with mouse occurs on the vnc session

**Comment by dcommander** [comment]
valgrind won't drop a core.  It should print a stack trace to the console whenever any errors are encountered.  You can pass `--db-attach=yes` to it in order to make it stop whenever an error is encountered and prompt you to start GDB at the error location.

**Comment by Cpmos** [comment]
Got it. And as you have predicted: crashing seems very difficult. Will run some production on this server and see what happens.

**Comment by Cpmos** [comment]
This is going to take very very long to find out. I am still on it but we will propably not be able to fix this because I simply can' t get it to crash in debug enviroment. 

If all else fails I still want to thank you so far for your patience and being very helpfull with this issue. 

I will report back in as soon as I manage to get some results.

**Comment by dcommander** [comment]
If you are unable to reproduce it, you should at least try to deploy a new build from the tip of master.  Numerous valgrind issues were fixed relative to 2.2, so there's a good chance that this issue was among them.

**Comment by dcommander** [comment]
Closing due to lack of response and my inability to reproduce the issue.
